<a href="https://colab.research.google.com/github/hakham99/Projects/blob/main/My_Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing The Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

#Importing the public dataset

In [3]:
dataset_1 = pd.read_csv('public_cars.csv')

In [4]:
dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30824 entries, 0 to 30823
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   manufacturer_name  30824 non-null  object 
 1   model_name         30824 non-null  object 
 2   transmission       30824 non-null  object 
 3   color              30824 non-null  object 
 4   odometer_value     30824 non-null  int64  
 5   year_produced      30824 non-null  int64  
 6   engine_fuel        30824 non-null  object 
 7   engine_has_gas     30824 non-null  bool   
 8   engine_type        30824 non-null  object 
 9   engine_capacity    30816 non-null  float64
 10  body_type          30824 non-null  object 
 11  has_warranty       30824 non-null  bool   
 12  state              30824 non-null  object 
 13  drivetrain         30824 non-null  object 
 14  feature_0          30824 non-null  bool   
 15  feature_1          30824 non-null  bool   
 16  feature_2          308

# Cleaning the Data

In [5]:
dataset_1.dropna(inplace=True)

In [6]:
dataset_1.shape

(30816, 26)

In [7]:
dataset_1.head()

manufacturer_name model_name  ... duration_listed price_usd
0              Ford     Fusion  ...               7    4250.0
1             Dodge    Caravan  ...             133    4000.0
2              Ford     Galaxy  ...               0   10900.0
3             Mazda          6  ...              20    6999.0
4              Audi         80  ...             160    1600.0

[5 rows x 26 columns]

In [8]:
dataset_1.drop(columns=[
                        'manufacturer_name', 
                        'model_name', 
                        'transmission', 
                        'color', 
                        'engine_fuel', 
                        'engine_type', 
                        'body_type', 
                        'state', 
                        'drivetrain'
                        ], 
               inplace=True)

In [9]:
dataset_1.head()

odometer_value  year_produced  ...  duration_listed  price_usd
0          245000           2006  ...                7     4250.0
1          265542           2002  ...              133     4000.0
2          168000           2009  ...                0    10900.0
3          225522           2008  ...               20     6999.0
4          370000           1991  ...              160     1600.0

[5 rows x 17 columns]

# Setting the the Independent and the Dependent sets 

In [10]:
X = dataset_1.iloc[:, :-1].values
y = dataset_1.iloc[:, -1].values

# Data Preprocessing

## Encoding the Catagorical data

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in range(16):
    if((i != 0) and (i != 1) and (i != 3) and (i != 15)):
        X[:, i] = le.fit_transform(X[:, i])

In [12]:
pd.DataFrame(X)

0     1  2    3  4  5  6  7  8  9  10 11 12 13 14   15
0      245000  2006  0  1.6  0  1  0  0  0  0  0  0  0  0  0    7
1      265542  2002  0  3.3  0  0  1  0  0  0  0  0  0  0  0  133
2      168000  2009  0  1.8  0  0  0  0  1  0  0  1  1  1  1    0
3      225522  2008  0  1.8  0  0  1  1  0  0  1  0  0  1  1   20
4      370000  1991  0  1.8  0  0  0  0  0  0  0  0  0  0  1  160
...       ...   ... ..  ... .. .. .. .. .. .. .. .. .. .. ..  ...
30811  360493  1999  0  2.5  0  0  1  0  0  1  1  0  0  0  1   66
30812  117000  2009  0  1.4  0  0  1  1  1  0  0  0  1  1  1   58
30813  333000  1997  0    2  0  0  0  0  0  0  0  0  0  0  1   87
30814  530000  1995  0  2.6  0  0  1  1  0  0  0  0  0  1  1   52
30815   15000  2018  0  3.5  0  0  1  1  1  1  1  1  1  1  1   75

[30816 rows x 16 columns]

##Splitting the data into training set and test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
X_train

array([[ 0., -0., -0., ..., -1., -1., -0.],
       [ 1., -0., -0., ...,  1., -1., -0.],
       [-2.,  2., -0., ..., -1., -1., -0.],
       ...,
       [ 1., -1., -0., ...,  1.,  1., -1.],
       [-1., -2., -0., ..., -1., -1., -0.],
       [ 0.,  0., -0., ..., -1., -1., -0.]])

## Scaling the Data

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training XGBoost on the taining set and predict the test set

In [21]:
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(X_train, y_train)

[10:42:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [17]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=0)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 4325.  4690.]
 [ 6649.  5500.]
 [10531.  9990.]
 ...
 [ 9716.  7000.]
 [ 1463.  1000.]
 [  956.   500.]]


# Applying k-Fold Cross Validation to evaluate the performence

In [22]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 10)
print("r2_Score: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[10:42:41] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:43] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:44] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:46] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:49] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[10:42:50] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of re

# Predicting New Data

## Importing the pred dataset

In [23]:
dataset_2 = pd.read_csv('pred_cars.csv')

In [24]:
dataset_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7707 entries, 0 to 7706
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   manufacturer_name  7707 non-null   object 
 1   model_name         7707 non-null   object 
 2   transmission       7707 non-null   object 
 3   color              7707 non-null   object 
 4   odometer_value     7707 non-null   int64  
 5   year_produced      7707 non-null   int64  
 6   engine_fuel        7707 non-null   object 
 7   engine_has_gas     7707 non-null   bool   
 8   engine_type        7707 non-null   object 
 9   engine_capacity    7705 non-null   float64
 10  body_type          7707 non-null   object 
 11  has_warranty       7707 non-null   bool   
 12  state              7707 non-null   object 
 13  drivetrain         7707 non-null   object 
 14  feature_0          7707 non-null   bool   
 15  feature_1          7707 non-null   bool   
 16  feature_2          7707 

## Cleaning the Data

In [25]:
dataset_2.dropna(inplace=True)

In [26]:
dataset_2.drop(columns=[
                        'manufacturer_name', 
                        'model_name', 
                        'transmission', 
                        'color', 
                        'engine_fuel', 
                        'engine_type', 
                        'body_type', 
                        'state', 
                        'drivetrain'
                        ], 
               inplace=True)

In [27]:
dataset_2.shape

(7705, 16)

##Setting the Independent set

In [28]:
X_pred = dataset_2.iloc[:, :].values

## Encoding the Catagorical data

In [29]:
for i in range(16):
    if((i != 0) and (i != 1) and (i != 3) and (i != 15)):
        X_pred[:, i] = le.transform(X_pred[:, i])

In [30]:
pd.DataFrame(X_pred)

0     1  2    3  4  5  6  7  8  9  10 11 12 13 14   15
0     360000  1997  0  1.6  0  0  1  0  0  0  0  0  1  0  1  114
1     267000  1999  0  1.4  0  0  0  0  0  0  0  0  0  0  1   67
2     172000  2000  0    2  0  1  0  0  0  0  0  0  0  0  0   50
3     230000  2009  0  2.4  0  0  1  1  1  0  1  1  1  1  1   79
4     206000  2007  0  1.6  0  0  1  0  1  0  1  0  0  0  0   74
...      ...   ... ..  ... .. .. .. .. .. .. .. .. .. .. ..  ...
7700  347618  2001  0  2.4  0  1  0  0  0  0  0  0  0  0  0   81
7701    9700  2018  0    2  0  0  1  0  1  0  1  0  1  1  1   84
7702  111111  2001  0  2.4  0  1  0  0  0  0  0  0  0  0  0    1
7703  109000  2016  0  1.5  0  0  0  0  1  0  0  1  1  1  1    2
7704  180000  2000  0  1.4  0  1  0  0  0  0  0  0  0  0  0   26

[7705 rows x 16 columns]

## Scaling the Data

In [31]:
X_pred = sc.transform(X_pred)

## Predicting the Data

In [46]:
y_pred = regressor.predict(X_pred)
np.set_printoptions(precision=0)
np.array(y_pred, int)

array([ 1962,  1797,  2886, ...,  3935, 13217,  1891])

## Upload the predictions

In [47]:
dataset_2['my-price-used'] = np.array(y_pred, int)

In [48]:
dataset_2

odometer_value  year_produced  ...  duration_listed  my-price-used
0             360000           1997  ...              114           1962
1             267000           1999  ...               67           1797
2             172000           2000  ...               50           2886
3             230000           2009  ...               79          12346
4             206000           2007  ...               74           5050
...              ...            ...  ...              ...            ...
7702          347618           2001  ...               81           4066
7703            9700           2018  ...               84          24127
7704          111111           2001  ...                1           3935
7705          109000           2016  ...                2          13217
7706          180000           2000  ...               26           1891

[7705 rows x 17 columns]

## Save to CSV

In [49]:
dataset_2.to_csv('my_predictions.csv')